### ISSUE TITLE
Automatic Publishing

### ISSUE THREAD

**Issue by jon-athan-hall** [jon-athan-hall/tiny-waste#12]
Right now, we have to:
* run `bundle exec jekyll build` locally
* move the `_site` file to the server with FTP
* copy that folder from `/jonathan/home` to `/var/www/html/tiny-waste`

It'd be nice to have all new changes go live automatically, using GitHub and the `master` branch.

**Comment by luigieai** [comment]
Hello, i want pratice my pipeline creation skills, can i help with this issue? I belive we can automate this process using Github Actions
